# .mergify.yml
pull_request_rules:
  - name: Auto-merge approved PRs
    conditions:
      - base = main
      - schedule = Mon-Fri 15:05-16:00[Asia/Karachi]
      - head = test-branch
    actions:
      merge:
        method: squash
