# name: Pull Request CI

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:
#       - production


# jobs:
#   build-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: validate source branch
#         if: ${{ !startsWith(github.head_ref, 'release/') }}
#         run: |

#             echo "Source branch must be release/*'. Failing the build."
#             exit 1
          

