name: Pull Request CI

on:
  pull_request:
    branches:
      - production


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: validate source branch
        if: ${{ !startsWith(github.event.pull_request.head.ref, 'main') }}
        run: |

            echo "Source branch cannot be 'production'. Failing the build."
            exit 1
          

